version: 2.1
jobs:
  build:
    docker:
      - image: cimg/gcc:12.3 # Updated docker image
    steps:
      - checkout # Checks out your code
      - run:
          name: "Build and Run"
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
            ./Pacman
workflows:
  build-and-run:
    jobs:
      - build